<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Symfony\Component\Finder\Finder;

/**
 * Detect and optionally remove orphaned translation keys.
 *
 * This command scans the codebase to find translation keys that are defined
 * in the translation files but not used anywhere in the code.
 *
 * Usage:
 *   sail artisan i18n:check-orphans              # List orphaned keys
 *   sail artisan i18n:check-orphans --fix        # Remove orphaned keys
 *   sail artisan i18n:check-orphans --namespace=admin  # Check specific namespace
 *
 * @see docs/plans/I18N-RESTRUCTURE-PLAN.md
 */
class CheckOrphanedTranslations extends Command
{
    protected $signature = 'i18n:check-orphans
                            {--fix : Remove orphaned keys automatically}
                            {--namespace=* : Check only specific namespaces}
                            {--ignore=* : Ignore specific key patterns}
                            {--verbose-keys : Show all orphaned keys, not just summary}';

    protected $description = 'Detect translation keys not used in the codebase';

    /**
     * Regex patterns to find translation key usage in code.
     *
     * @var array<string>
     */
    protected array $usagePatterns = [
        // t('key'), t("key")
        '/\bt\s*\(\s*[\'"]([^\'"]+)[\'"]\s*(?:,|\))/s',
        // tChoice('key', ...)
        '/\btChoice\s*\(\s*[\'"]([^\'"]+)[\'"]\s*,/s',
        // trans('key'), __('key')
        '/\b(?:trans|__)\s*\(\s*[\'"]([^\'"]+)[\'"]\s*(?:,|\))/s',
        // Lang::get('key')
        '/Lang::get\s*\(\s*[\'"]([^\'"]+)[\'"]\s*(?:,|\))/s',
        // Translation keys in PHP arrays (for enums, etc.)
        '/[\'"]translation_key[\'"]\s*=>\s*[\'"]([^\'"]+)[\'"]/s',
        // Flash messages from controllers
        '/->with\s*\(\s*[\'"](?:success|error|warning|info)[\'"]\s*,\s*[\'"]([^\'"]+)[\'"]\)/s',
    ];

    /**
     * Key patterns that are used dynamically (not literal strings in code).
     *
     * @var array<string>
     */
    protected array $dynamicKeyPatterns = [
        'enums.*',           // Generated by types:generate
        'permissions.*',     // Generated by types:generate
        'validation.*',      // Used internally by Laravel
        'flash.*',           // Used via backend controllers
        'roles.*',           // Role names are dynamic
        'badges.*',          // Badge labels
        'billing.email.*',   // Email templates use these dynamically
        'billing.payment_methods.*', // Payment method labels
        'admin.audit.*',     // Shared audit component uses ${prefix}.key
        'tenant.audit.*',    // Shared audit component uses ${prefix}.key
        'tenant.activity.*', // Activity log component uses ${prefix}.key
        'admin.federation.user_status.*',  // StatusBadge uses ${status}
        'admin.federation.link_status.*',  // StatusBadge uses ${status}
        'admin.federation.conflict.*',     // Conflict status badges
    ];

    /**
     * Directories to scan for translation usage.
     *
     * @var array<string>
     */
    protected array $scanDirectories = [
        'resources/js',
        'resources/views',
        'app',
    ];

    /**
     * File extensions to scan.
     *
     * @var array<string>
     */
    protected array $scanExtensions = [
        '*.tsx',
        '*.ts',
        '*.php',
        '*.blade.php',
    ];

    public function handle(): int
    {
        $this->displayHeader();

        // 1. Collect all defined keys
        $definedKeys = $this->collectDefinedKeys();
        $this->info('  Defined keys: '.count($definedKeys));

        // 2. Collect all used keys in code
        $usedKeys = $this->collectUsedKeys();
        $this->info('  Keys found in code: '.count($usedKeys));

        // 3. Find orphans
        $orphans = $this->findOrphans($definedKeys, $usedKeys);

        // 4. Filter dynamic keys
        $orphans = $this->filterDynamicKeys($orphans);

        // 5. Filter by namespace if specified
        $namespaceFilter = $this->option('namespace');
        if (! empty($namespaceFilter)) {
            $orphans = $this->filterByNamespace($orphans, $namespaceFilter);
        }

        $this->newLine();

        if (empty($orphans)) {
            $this->info('  No orphaned keys found!');

            return self::SUCCESS;
        }

        $this->displayOrphans($orphans);

        // Option to fix
        if ($this->option('fix')) {
            return $this->removeOrphanedKeys($orphans);
        }

        $this->newLine();
        $this->info('  Run with --fix to remove orphaned keys');

        return self::SUCCESS;
    }

    protected function displayHeader(): void
    {
        $this->info('');
        $this->info('  ╔══════════════════════════════════════════════════════════╗');
        $this->info('  ║  Translation Orphan Checker                              ║');
        $this->info('  ╚══════════════════════════════════════════════════════════╝');
        $this->newLine();
    }

    /**
     * Collect all defined translation keys from files.
     *
     * @return array<string>
     */
    protected function collectDefinedKeys(): array
    {
        $keys = [];
        $baseLocale = config('app.fallback_locale', 'en');

        // Check for namespace-based structure first (supports nested folders)
        $dir = lang_path($baseLocale);

        if (File::isDirectory($dir)) {
            // Use File::allFiles for recursive scanning
            foreach (File::allFiles($dir) as $file) {
                if ($file->getExtension() === 'json') {
                    $translations = json_decode(File::get($file->getPathname()), true) ?? [];
                    $keys = array_merge($keys, array_keys($translations));
                }
            }
        } else {
            // Fallback to monolithic file
            $file = lang_path("{$baseLocale}.json");

            if (File::exists($file)) {
                $translations = json_decode(File::get($file), true) ?? [];
                $keys = array_keys($translations);
            }
        }

        return array_unique($keys);
    }

    /**
     * Collect all translation keys used in the codebase.
     *
     * @return array<string>
     */
    protected function collectUsedKeys(): array
    {
        $usedKeys = [];

        $finder = new Finder;
        $finder->files()
            ->in(array_map(fn ($dir) => base_path($dir), $this->scanDirectories))
            ->name($this->scanExtensions)
            ->exclude(['vendor', 'node_modules', '.git']);

        foreach ($finder as $file) {
            $content = $file->getContents();

            foreach ($this->usagePatterns as $pattern) {
                if (preg_match_all($pattern, $content, $matches)) {
                    $usedKeys = array_merge($usedKeys, $matches[1]);
                }
            }
        }

        // Add custom ignore patterns from command line
        $customIgnores = $this->option('ignore');
        foreach ($customIgnores as $pattern) {
            $usedKeys[] = $pattern;
        }

        return array_unique($usedKeys);
    }

    /**
     * Find keys that are defined but not used.
     *
     * @return array<string>
     */
    protected function findOrphans(array $defined, array $used): array
    {
        return array_values(array_diff($defined, $used));
    }

    /**
     * Filter out keys that are used dynamically.
     *
     * @return array<string>
     */
    protected function filterDynamicKeys(array $orphans): array
    {
        return array_values(array_filter($orphans, function ($key) {
            foreach ($this->dynamicKeyPatterns as $pattern) {
                // Order matters: escape dots first, then convert * to .*
                $regex = '/^'.str_replace(['.', '*'], ['\.', '.*'], $pattern).'$/';

                if (preg_match($regex, $key)) {
                    return false;
                }
            }

            return true;
        }));
    }

    /**
     * Filter orphans by namespace.
     *
     * @param  array<string>  $namespaces
     * @return array<string>
     */
    protected function filterByNamespace(array $orphans, array $namespaces): array
    {
        return array_values(array_filter($orphans, function ($key) use ($namespaces) {
            $keyNamespace = explode('.', $key)[0];

            return in_array($keyNamespace, $namespaces);
        }));
    }

    /**
     * Display orphaned keys grouped by namespace.
     */
    protected function displayOrphans(array $orphans): void
    {
        $grouped = $this->groupByNamespace($orphans);

        $this->warn('  Found '.count($orphans).' potentially orphaned keys:');
        $this->newLine();

        foreach ($grouped as $namespace => $keys) {
            $count = count($keys);
            $this->line("  [{$namespace}] {$count} keys:");

            if ($this->option('verbose-keys') || $count <= 10) {
                foreach ($keys as $key) {
                    $this->line("    - {$key}");
                }
            } else {
                foreach (array_slice($keys, 0, 5) as $key) {
                    $this->line("    - {$key}");
                }
                $this->line('    ... and '.($count - 5).' more');
            }

            $this->newLine();
        }

        // Show dynamic patterns info
        $this->info('  Note: Keys matching these patterns are ignored (used dynamically):');
        foreach ($this->dynamicKeyPatterns as $pattern) {
            $this->line("    - {$pattern}");
        }
    }

    /**
     * Group keys by their namespace (first part before dot).
     *
     * @return array<string, array<string>>
     */
    protected function groupByNamespace(array $keys): array
    {
        $grouped = [];

        foreach ($keys as $key) {
            $parts = explode('.', $key);
            $namespace = $parts[0];
            $grouped[$namespace][] = $key;
        }

        ksort($grouped);

        return $grouped;
    }

    /**
     * Remove orphaned keys from all translation files.
     */
    protected function removeOrphanedKeys(array $orphans): int
    {
        if (! $this->confirm('Remove '.count($orphans).' orphaned keys from all locales?')) {
            return self::SUCCESS;
        }

        $locales = config('app.locales', ['en', 'pt_BR', 'es']);
        $totalRemoved = 0;

        foreach ($locales as $locale) {
            $removed = $this->removeOrphansFromLocale($locale, $orphans);
            $totalRemoved += $removed;
        }

        $this->newLine();
        $this->info("  Removed {$totalRemoved} keys across all locales.");
        $this->info('  Run "sail artisan types:generate" to update TypeScript types.');

        return self::SUCCESS;
    }

    /**
     * Remove orphans from a specific locale.
     */
    protected function removeOrphansFromLocale(string $locale, array $orphans): int
    {
        $removed = 0;
        $dir = lang_path($locale);

        // Handle namespace-based structure (supports nested folders)
        if (File::isDirectory($dir)) {
            // Use File::allFiles for recursive scanning
            foreach (File::allFiles($dir) as $file) {
                if ($file->getExtension() !== 'json') {
                    continue;
                }

                $filePath = $file->getPathname();
                $translations = json_decode(File::get($filePath), true) ?? [];
                $originalCount = count($translations);

                foreach ($orphans as $orphan) {
                    unset($translations[$orphan]);
                }

                $newCount = count($translations);
                $fileRemoved = $originalCount - $newCount;

                if ($fileRemoved > 0) {
                    ksort($translations);
                    $json = json_encode($translations, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
                    File::put($filePath, $json."\n");
                    // Show relative path from locale dir
                    $relativePath = str_replace($dir.'/', '', $filePath);
                    $this->line("  ✓ {$locale}/{$relativePath}: removed {$fileRemoved} keys");
                    $removed += $fileRemoved;
                }
            }
        } else {
            // Handle monolithic file
            $file = lang_path("{$locale}.json");

            if (File::exists($file)) {
                $translations = json_decode(File::get($file), true) ?? [];
                $originalCount = count($translations);

                foreach ($orphans as $orphan) {
                    unset($translations[$orphan]);
                }

                $newCount = count($translations);
                $removed = $originalCount - $newCount;

                if ($removed > 0) {
                    ksort($translations);
                    $json = json_encode($translations, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
                    File::put($file, $json."\n");
                    $this->line("  ✓ {$locale}.json: removed {$removed} keys");
                }
            }
        }

        return $removed;
    }
}
