<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class GeneratePermissionTypes extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'permissions:generate-types {--show : Only show output without writing file}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate TypeScript types from SyncPermissions command';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $this->info('🔧 Generating TypeScript permission types...');
        $this->newLine();

        try {
            // Get permissions from SyncPermissions command
            $syncCommand = new SyncPermissions();
            $reflection = new \ReflectionClass($syncCommand);
            $property = $reflection->getProperty('permissions');
            $property->setAccessible(true);
            $permissions = $property->getValue($syncCommand);

            // Extract permission data
            $permissionNames = [];
            $categories = [];
            $actions = [];

            foreach ($permissions as $perm) {
                $name = $perm['name'];
                $description = $perm['description'];
                $category = $perm['category'];

                $permissionNames[] = [
                    'name' => $name,
                    'description' => $description,
                    'category' => $category,
                ];

                // Extract category and action from name (format: tenant.category:action)
                if (preg_match('/^tenant\.([^:]+):(.+)$/', $name, $matches)) {
                    $categories[$matches[1]] = true;
                    $actions[$matches[2]] = true;
                }
            }

            // Generate TypeScript content
            $typescript = $this->generateTypeScriptContent($permissionNames, array_keys($categories), array_keys($actions));

            // Show or write file
            if ($this->option('show')) {
                $this->line($typescript);
            } else {
                $outputPath = resource_path('js/types/permissions.d.ts');
                File::put($outputPath, $typescript);
                $this->info("✅ TypeScript types generated: {$outputPath}");
            }

            $this->newLine();
            $this->info("📊 Summary:");
            $this->line("  • Permissions: " . count($permissionNames));
            $this->line("  • Categories: " . implode(', ', array_keys($categories)));
            $this->line("  • Actions: " . implode(', ', array_keys($actions)));

            return self::SUCCESS;
        } catch (\Exception $e) {
            $this->error("❌ Error: {$e->getMessage()}");
            return self::FAILURE;
        }
    }

    /**
     * Generate TypeScript content
     */
    protected function generateTypeScriptContent(array $permissions, array $categories, array $actions): string
    {
        $timestamp = now()->toDateTimeString();

        // Build Permission union type with JSDoc comments
        $permissionUnion = collect($permissions)
            ->map(fn($p) => "  | '{$p['name']}'  // {$p['description']}")
            ->join("\n");

        // Build category-specific permission types
        $categoryTypes = collect($categories)
            ->map(function ($category) use ($permissions) {
                $categoryPerms = collect($permissions)
                    ->filter(fn($p) => $p['category'] === $category)
                    ->map(fn($p) => "  | '{$p['name']}'  // {$p['description']}")
                    ->join("\n");

                $capitalizedCategory = ucfirst($category);
                return <<<TS
/**
 * {$capitalizedCategory} permissions
 */
export type {$capitalizedCategory}Permission =
{$categoryPerms};
TS;
            })
            ->join("\n\n");

        return <<<TS
/**
 * Auto-generated TypeScript types for Laravel permissions
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated at: {$timestamp}
 *
 * To regenerate, run: php artisan permissions:generate-types
 * This file is automatically regenerated when running: php artisan permissions:sync
 */

/**
 * All available permissions in the system
 * Format: tenant.<category>:<action>
 */
export type Permission =
{$permissionUnion};

{$categoryTypes}

/**
 * Role metadata (for UI display only - NOT for authorization)
 */
export interface Role {
  /** Role name (owner, admin, member) */
  name: string | null;

  /** Is user owner of tenant? (for UI badges/display) */
  isOwner: boolean;

  /** Is user admin? (for UI badges/display) */
  isAdmin: boolean;

  /** Is user admin or owner? (for UI badges/display) */
  isAdminOrOwner: boolean;

  /** Is user a Super Admin? (global platform admin - for UI badges/display) */
  isSuperAdmin: boolean;
}

/**
 * Authentication state with permissions
 */
export interface Auth {
  /** Current authenticated user */
  user: any | null;

  /**
   * Array of permission names the user HAS (not all with booleans)
   * Use with: permissions.includes('tenant.projects:view')
   * Or better: usePermissions().has('tenant.projects:view')
   */
  permissions: Permission[];

  /**
   * Role metadata (for UI only - badges, display names, etc)
   * WARNING: Do NOT use for authorization! Use permissions instead.
   */
  role: Role | null;
}

/**
 * Permission categories available in the system
 */
export type PermissionCategory = 'projects' | 'team' | 'settings' | 'billing';

/**
 * Permission actions available in the system
 */
export type PermissionAction =
  | 'view'
  | 'create'
  | 'edit'
  | 'edit-own'
  | 'delete'
  | 'upload'
  | 'download'
  | 'archive'
  | 'invite'
  | 'remove'
  | 'manage-roles'
  | 'activity'
  | 'danger'
  | 'manage'
  | 'invoices';

TS;
    }
}
