<?php

namespace App\Console\Commands;

use App\Enums\CentralPermission;
use App\Enums\TenantPermission;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class GeneratePermissionTypes extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'permissions:generate-types {--show : Only show output without writing file}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate TypeScript types from Permission Enums (single source of truth)';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $this->info('🔧 Generating TypeScript permission types from enums...');
        $this->newLine();

        try {
            // Get permissions from enums (single source of truth)
            $tenantPermissions = collect(TenantPermission::cases())->map(fn ($p) => [
                'name' => $p->value,
                'description' => $p->description()['en'] ?? '',
                'category' => $p->category(),
                'source' => 'tenant',
            ]);

            $centralPermissions = collect(CentralPermission::cases())->map(fn ($p) => [
                'name' => $p->value,
                'description' => $p->description()['en'] ?? '',
                'category' => $p->category(),
                'source' => 'central',
            ]);

            // Merge and deduplicate by name (keep first occurrence)
            $allPermissions = $tenantPermissions
                ->merge($centralPermissions)
                ->unique('name')
                ->values()
                ->toArray();

            // Extract unique categories and actions
            $categories = collect($allPermissions)->pluck('category')->unique()->sort()->values()->toArray();
            $actions = collect($allPermissions)
                ->map(fn ($p) => explode(':', $p['name'])[1] ?? '')
                ->filter()
                ->unique()
                ->sort()
                ->values()
                ->toArray();

            // Generate TypeScript content
            $typescript = $this->generateTypeScriptContent($allPermissions, $categories, $actions);

            // Show or write file
            if ($this->option('show')) {
                $this->line($typescript);
            } else {
                $outputPath = resource_path('js/types/permissions.d.ts');
                File::put($outputPath, $typescript);
                $this->info("✅ TypeScript types generated: {$outputPath}");
            }

            $this->newLine();
            $this->info("📊 Summary:");
            $this->line("  • Total unique permissions: " . count($allPermissions));
            $this->line("  • Tenant permissions: " . count($tenantPermissions));
            $this->line("  • Central permissions: " . count($centralPermissions));
            $this->line("  • Categories: " . implode(', ', $categories));

            return self::SUCCESS;
        } catch (\Exception $e) {
            $this->error("❌ Error: {$e->getMessage()}");
            return self::FAILURE;
        }
    }

    /**
     * Generate TypeScript content
     */
    protected function generateTypeScriptContent(array $permissions, array $categories, array $actions): string
    {
        $timestamp = now()->toDateTimeString();

        // Build Permission union type with JSDoc comments (unique permissions only)
        $permissionUnion = collect($permissions)
            ->map(fn ($p) => "  | '{$p['name']}'  // {$p['description']}")
            ->join("\n");

        // Build category-specific permission types
        $categoryTypes = collect($categories)
            ->map(function ($category) use ($permissions) {
                $categoryPerms = collect($permissions)
                    ->filter(fn ($p) => $p['category'] === $category)
                    ->map(fn ($p) => "  | '{$p['name']}'  // {$p['description']}")
                    ->join("\n");

                if (empty($categoryPerms)) {
                    return '';
                }

                $capitalizedCategory = ucfirst($category);
                return <<<TS
/**
 * {$capitalizedCategory} permissions
 */
export type {$capitalizedCategory}Permission =
{$categoryPerms};
TS;
            })
            ->filter()
            ->join("\n\n");

        // Build categories union
        $categoriesUnion = collect($categories)
            ->map(fn ($c) => "  | '{$c}'")
            ->join("\n");

        // Build actions union
        $actionsUnion = collect($actions)
            ->map(fn ($a) => "  | '{$a}'")
            ->join("\n");

        return <<<TS
/**
 * Auto-generated TypeScript types for Laravel permissions
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated at: {$timestamp}
 *
 * Source: TenantPermission and CentralPermission enums (single source of truth)
 *
 * To regenerate, run: php artisan permissions:generate-types
 * This file is automatically regenerated when running: php artisan permissions:sync
 */

/**
 * All available permissions in the system
 * Format: <category>:<action>
 *
 * Note: Some permissions exist in both tenant and central contexts
 * (e.g., roles:view). The TypeScript type is deduplicated.
 */
export type Permission =
{$permissionUnion};

{$categoryTypes}

/**
 * Permission categories available in the system
 */
export type PermissionCategory =
{$categoriesUnion};

/**
 * Permission actions available in the system
 */
export type PermissionAction =
{$actionsUnion};

/**
 * Role metadata (for UI display only - NOT for authorization)
 */
export interface Role {
  /** Role name (owner, admin, member) */
  name: string | null;

  /** Is user owner of tenant? (for UI badges/display) */
  isOwner: boolean;

  /** Is user admin? (for UI badges/display) */
  isAdmin: boolean;

  /** Is user admin or owner? (for UI badges/display) */
  isAdminOrOwner: boolean;

  /** Is user a Super Admin? (global platform admin - for UI badges/display) */
  isSuperAdmin: boolean;
}

/**
 * Authentication state with permissions
 * Note: User type should be imported from your app's types (e.g., @/types)
 */
export interface Auth<TUser = unknown> {
  /** Current authenticated user */
  user: TUser | null;

  /**
   * Array of permission names the user HAS (not all with booleans)
   * Use with: permissions.includes('projects:view')
   * Or better: usePermissions().has('projects:view')
   */
  permissions: Permission[];

  /**
   * Role metadata (for UI only - badges, display names, etc)
   * WARNING: Do NOT use for authorization! Use permissions instead.
   */
  role: Role | null;
}

TS;
    }
}
