services:
  laravel.test:
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal start_with_request=yes"
      PHP_IDE_CONFIG: "serverName=localhost"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - './.docker/php/conf.d/xdebug.ini:/etc/php/8.4/cli/conf.d/99-xdebug.ini'   
      - './.docker/php/conf.d/xdebug.ini:/etc/php/8.4/fpm/conf.d/99-xdebug.ini'