/**
 * Auto-generated TypeScript types for Laravel permissions
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated at: 2025-12-06 16:16:02
 *
 * Source: TenantPermission and CentralPermission enums (single source of truth)
 *
 * To regenerate, run: php artisan permissions:generate-types
 * This file is automatically regenerated when running: php artisan permissions:sync
 */

/**
 * All available permissions in the system
 * Format: <category>:<action>
 *
 * Note: Some permissions exist in both tenant and central contexts
 * (e.g., roles:view). The TypeScript type is deduplicated.
 */
export type Permission =
  | 'projects:view'  // View all projects
  | 'projects:create'  // Create new projects
  | 'projects:edit'  // Edit any project
  | 'projects:editOwn'  // Edit own projects only
  | 'projects:delete'  // Delete projects
  | 'projects:upload'  // Upload files
  | 'projects:download'  // Download files
  | 'projects:archive'  // Archive projects
  | 'team:view'  // View team members
  | 'team:invite'  // Invite members
  | 'team:remove'  // Remove members
  | 'team:manageRoles'  // Manage roles
  | 'team:activity'  // View activity logs
  | 'settings:view'  // View settings
  | 'settings:edit'  // Edit settings
  | 'settings:danger'  // Danger zone access
  | 'billing:view'  // View billing
  | 'billing:manage'  // Manage subscriptions
  | 'billing:invoices'  // Download invoices
  | 'apiTokens:view'  // View API tokens
  | 'apiTokens:create'  // Create API tokens
  | 'apiTokens:delete'  // Delete API tokens
  | 'roles:view'  // View custom roles
  | 'roles:create'  // Create custom roles
  | 'roles:edit'  // Edit custom roles
  | 'roles:delete'  // Delete custom roles
  | 'reports:view'  // View reports
  | 'reports:export'  // Export reports
  | 'reports:schedule'  // Schedule reports
  | 'reports:customize'  // Customize reports
  | 'sso:configure'  // Configure SSO
  | 'sso:manage'  // Manage SSO providers
  | 'sso:testConnection'  // Test SSO connection
  | 'branding:view'  // View branding
  | 'branding:edit'  // Edit branding
  | 'branding:preview'  // Preview branding
  | 'branding:publish'  // Publish branding
  | 'audit:view'  // View audit logs
  | 'audit:export'  // Export audit logs
  | 'locales:view'  // View language settings
  | 'locales:manage'  // Manage language settings
  | 'tenants:view'  // View all tenants
  | 'tenants:show'  // View tenant details
  | 'tenants:edit'  // Edit tenant settings
  | 'tenants:delete'  // Delete tenants
  | 'tenants:impersonate'  // Impersonate tenant users
  | 'users:view'  // View all users
  | 'users:show'  // View user details
  | 'users:edit'  // Edit user details
  | 'users:delete'  // Delete users
  | 'plans:view'  // View all plans
  | 'plans:create'  // Create new plans
  | 'plans:edit'  // Edit plans
  | 'plans:delete'  // Delete plans
  | 'plans:sync'  // Sync plans with Stripe
  | 'catalog:view'  // View addon catalog
  | 'catalog:create'  // Create new addons
  | 'catalog:edit'  // Edit addons
  | 'catalog:delete'  // Delete addons
  | 'catalog:sync'  // Sync addons with Stripe
  | 'addons:view'  // View tenant addons
  | 'addons:revenue'  // View addon revenue reports
  | 'addons:grant'  // Grant addons to tenants
  | 'addons:revoke'  // Revoke addons from tenants
  | 'system:view'  // View system settings
  | 'system:edit'  // Edit system settings
  | 'system:logs'  // View system logs;

/**
 * Addons permissions
 */
export type AddonsPermission =
  | 'addons:view'  // View tenant addons
  | 'addons:revenue'  // View addon revenue reports
  | 'addons:grant'  // Grant addons to tenants
  | 'addons:revoke'  // Revoke addons from tenants;

/**
 * ApiTokens permissions
 */
export type ApiTokensPermission =
  | 'apiTokens:view'  // View API tokens
  | 'apiTokens:create'  // Create API tokens
  | 'apiTokens:delete'  // Delete API tokens;

/**
 * Audit permissions
 */
export type AuditPermission =
  | 'audit:view'  // View audit logs
  | 'audit:export'  // Export audit logs;

/**
 * Billing permissions
 */
export type BillingPermission =
  | 'billing:view'  // View billing
  | 'billing:manage'  // Manage subscriptions
  | 'billing:invoices'  // Download invoices;

/**
 * Branding permissions
 */
export type BrandingPermission =
  | 'branding:view'  // View branding
  | 'branding:edit'  // Edit branding
  | 'branding:preview'  // Preview branding
  | 'branding:publish'  // Publish branding;

/**
 * Catalog permissions
 */
export type CatalogPermission =
  | 'catalog:view'  // View addon catalog
  | 'catalog:create'  // Create new addons
  | 'catalog:edit'  // Edit addons
  | 'catalog:delete'  // Delete addons
  | 'catalog:sync'  // Sync addons with Stripe;

/**
 * Locales permissions
 */
export type LocalesPermission =
  | 'locales:view'  // View language settings
  | 'locales:manage'  // Manage language settings;

/**
 * Plans permissions
 */
export type PlansPermission =
  | 'plans:view'  // View all plans
  | 'plans:create'  // Create new plans
  | 'plans:edit'  // Edit plans
  | 'plans:delete'  // Delete plans
  | 'plans:sync'  // Sync plans with Stripe;

/**
 * Projects permissions
 */
export type ProjectsPermission =
  | 'projects:view'  // View all projects
  | 'projects:create'  // Create new projects
  | 'projects:edit'  // Edit any project
  | 'projects:editOwn'  // Edit own projects only
  | 'projects:delete'  // Delete projects
  | 'projects:upload'  // Upload files
  | 'projects:download'  // Download files
  | 'projects:archive'  // Archive projects;

/**
 * Reports permissions
 */
export type ReportsPermission =
  | 'reports:view'  // View reports
  | 'reports:export'  // Export reports
  | 'reports:schedule'  // Schedule reports
  | 'reports:customize'  // Customize reports;

/**
 * Roles permissions
 */
export type RolesPermission =
  | 'roles:view'  // View custom roles
  | 'roles:create'  // Create custom roles
  | 'roles:edit'  // Edit custom roles
  | 'roles:delete'  // Delete custom roles;

/**
 * Settings permissions
 */
export type SettingsPermission =
  | 'settings:view'  // View settings
  | 'settings:edit'  // Edit settings
  | 'settings:danger'  // Danger zone access;

/**
 * Sso permissions
 */
export type SsoPermission =
  | 'sso:configure'  // Configure SSO
  | 'sso:manage'  // Manage SSO providers
  | 'sso:testConnection'  // Test SSO connection;

/**
 * System permissions
 */
export type SystemPermission =
  | 'system:view'  // View system settings
  | 'system:edit'  // Edit system settings
  | 'system:logs'  // View system logs;

/**
 * Team permissions
 */
export type TeamPermission =
  | 'team:view'  // View team members
  | 'team:invite'  // Invite members
  | 'team:remove'  // Remove members
  | 'team:manageRoles'  // Manage roles
  | 'team:activity'  // View activity logs;

/**
 * Tenants permissions
 */
export type TenantsPermission =
  | 'tenants:view'  // View all tenants
  | 'tenants:show'  // View tenant details
  | 'tenants:edit'  // Edit tenant settings
  | 'tenants:delete'  // Delete tenants
  | 'tenants:impersonate'  // Impersonate tenant users;

/**
 * Users permissions
 */
export type UsersPermission =
  | 'users:view'  // View all users
  | 'users:show'  // View user details
  | 'users:edit'  // Edit user details
  | 'users:delete'  // Delete users;

/**
 * Permission categories available in the system
 */
export type PermissionCategory =
  | 'addons'
  | 'apiTokens'
  | 'audit'
  | 'billing'
  | 'branding'
  | 'catalog'
  | 'locales'
  | 'plans'
  | 'projects'
  | 'reports'
  | 'roles'
  | 'settings'
  | 'sso'
  | 'system'
  | 'team'
  | 'tenants'
  | 'users';

/**
 * Permission actions available in the system
 */
export type PermissionAction =
  | 'activity'
  | 'archive'
  | 'configure'
  | 'create'
  | 'customize'
  | 'danger'
  | 'delete'
  | 'download'
  | 'edit'
  | 'editOwn'
  | 'export'
  | 'grant'
  | 'impersonate'
  | 'invite'
  | 'invoices'
  | 'logs'
  | 'manage'
  | 'manageRoles'
  | 'preview'
  | 'publish'
  | 'remove'
  | 'revenue'
  | 'revoke'
  | 'schedule'
  | 'show'
  | 'sync'
  | 'testConnection'
  | 'upload'
  | 'view';

/**
 * Role metadata (for UI display only - NOT for authorization)
 */
export interface Role {
  /** Role name (owner, admin, member) */
  name: string | null;

  /** Is user owner of tenant? (for UI badges/display) */
  isOwner: boolean;

  /** Is user admin? (for UI badges/display) */
  isAdmin: boolean;

  /** Is user admin or owner? (for UI badges/display) */
  isAdminOrOwner: boolean;

  /** Is user a Super Admin? (global platform admin - for UI badges/display) */
  isSuperAdmin: boolean;
}

/**
 * Authentication state with permissions
 * Note: User type should be imported from your app's types (e.g., @/types)
 */
export interface Auth<TUser = unknown> {
  /** Current authenticated user */
  user: TUser | null;

  /**
   * Array of permission names the user HAS (not all with booleans)
   * Use with: permissions.includes('projects:view')
   * Or better: usePermissions().has('projects:view')
   */
  permissions: Permission[];

  /**
   * Role metadata (for UI only - badges, display names, etc)
   * WARNING: Do NOT use for authorization! Use permissions instead.
   */
  role: Role | null;
}
