/**
 * Auto-generated TypeScript types for Laravel permissions
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated at: 2025-11-21 01:46:51
 *
 * To regenerate, run: php artisan permissions:generate-types
 * This file is automatically regenerated when running: php artisan permissions:sync
 */

/**
 * All available permissions in the system
 * Format: tenant.<category>:<action>
 */
export type Permission =
  | 'tenant.projects:view'  // View all projects
  | 'tenant.projects:create'  // Create new projects
  | 'tenant.projects:edit'  // Edit any project
  | 'tenant.projects:editOwn'  // Edit own projects only
  | 'tenant.projects:delete'  // Delete projects
  | 'tenant.projects:upload'  // Upload files
  | 'tenant.projects:download'  // Download files
  | 'tenant.projects:archive'  // Archive projects
  | 'tenant.team:view'  // View team members
  | 'tenant.team:invite'  // Invite members
  | 'tenant.team:remove'  // Remove members
  | 'tenant.team:manageRoles'  // Manage roles
  | 'tenant.team:activity'  // View activity logs
  | 'tenant.settings:view'  // View settings
  | 'tenant.settings:edit'  // Edit settings
  | 'tenant.settings:danger'  // Danger zone access
  | 'tenant.billing:view'  // View billing
  | 'tenant.billing:manage'  // Manage subscriptions
  | 'tenant.billing:invoices'  // Download invoices
  | 'tenant.apiTokens:view'  // View API tokens
  | 'tenant.apiTokens:create'  // Create API tokens
  | 'tenant.apiTokens:delete'  // Delete API tokens
  | 'tenant.roles:view'  // View custom roles
  | 'tenant.roles:create'  // Create custom roles
  | 'tenant.roles:edit'  // Edit custom roles
  | 'tenant.roles:delete'  // Delete custom roles
  | 'tenant.reports:view'  // View reports
  | 'tenant.reports:export'  // Export reports
  | 'tenant.reports:schedule'  // Schedule reports
  | 'tenant.reports:customize'  // Customize reports
  | 'tenant.sso:configure'  // Configure SSO
  | 'tenant.sso:manage'  // Manage SSO providers
  | 'tenant.sso:testConnection'  // Test SSO connection
  | 'tenant.branding:view'  // View branding
  | 'tenant.branding:edit'  // Edit branding
  | 'tenant.branding:preview'  // Preview branding
  | 'tenant.branding:publish'  // Publish branding;

/**
 * Projects permissions
 */
export type ProjectsPermission =
  | 'tenant.projects:view'  // View all projects
  | 'tenant.projects:create'  // Create new projects
  | 'tenant.projects:edit'  // Edit any project
  | 'tenant.projects:editOwn'  // Edit own projects only
  | 'tenant.projects:delete'  // Delete projects
  | 'tenant.projects:upload'  // Upload files
  | 'tenant.projects:download'  // Download files
  | 'tenant.projects:archive'  // Archive projects;

/**
 * Team permissions
 */
export type TeamPermission =
  | 'tenant.team:view'  // View team members
  | 'tenant.team:invite'  // Invite members
  | 'tenant.team:remove'  // Remove members
  | 'tenant.team:manageRoles'  // Manage roles
  | 'tenant.team:activity'  // View activity logs;

/**
 * Settings permissions
 */
export type SettingsPermission =
  | 'tenant.settings:view'  // View settings
  | 'tenant.settings:edit'  // Edit settings
  | 'tenant.settings:danger'  // Danger zone access;

/**
 * Billing permissions
 */
export type BillingPermission =
  | 'tenant.billing:view'  // View billing
  | 'tenant.billing:manage'  // Manage subscriptions
  | 'tenant.billing:invoices'  // Download invoices;

/**
 * ApiTokens permissions
 */
export type ApiTokensPermission =
  | 'tenant.apiTokens:view'  // View API tokens
  | 'tenant.apiTokens:create'  // Create API tokens
  | 'tenant.apiTokens:delete'  // Delete API tokens;

/**
 * Roles permissions
 */
export type RolesPermission =
  | 'tenant.roles:view'  // View custom roles
  | 'tenant.roles:create'  // Create custom roles
  | 'tenant.roles:edit'  // Edit custom roles
  | 'tenant.roles:delete'  // Delete custom roles;

/**
 * Reports permissions
 */
export type ReportsPermission =
  | 'tenant.reports:view'  // View reports
  | 'tenant.reports:export'  // Export reports
  | 'tenant.reports:schedule'  // Schedule reports
  | 'tenant.reports:customize'  // Customize reports;

/**
 * Sso permissions
 */
export type SsoPermission =
  | 'tenant.sso:configure'  // Configure SSO
  | 'tenant.sso:manage'  // Manage SSO providers
  | 'tenant.sso:testConnection'  // Test SSO connection;

/**
 * Branding permissions
 */
export type BrandingPermission =
  | 'tenant.branding:view'  // View branding
  | 'tenant.branding:edit'  // Edit branding
  | 'tenant.branding:preview'  // Preview branding
  | 'tenant.branding:publish'  // Publish branding;

/**
 * Role metadata (for UI display only - NOT for authorization)
 */
export interface Role {
  /** Role name (owner, admin, member) */
  name: string | null;

  /** Is user owner of tenant? (for UI badges/display) */
  isOwner: boolean;

  /** Is user admin? (for UI badges/display) */
  isAdmin: boolean;

  /** Is user admin or owner? (for UI badges/display) */
  isAdminOrOwner: boolean;

  /** Is user a Super Admin? (global platform admin - for UI badges/display) */
  isSuperAdmin: boolean;
}

/**
 * Authentication state with permissions
 */
export interface Auth {
  /** Current authenticated user */
  user: any | null;

  /**
   * Array of permission names the user HAS (not all with booleans)
   * Use with: permissions.includes('tenant.projects:view')
   * Or better: usePermissions().has('tenant.projects:view')
   */
  permissions: Permission[];

  /**
   * Role metadata (for UI only - badges, display names, etc)
   * WARNING: Do NOT use for authorization! Use permissions instead.
   */
  role: Role | null;
}

/**
 * Permission categories available in the system
 */
export type PermissionCategory = 'projects' | 'team' | 'settings' | 'billing';

/**
 * Permission actions available in the system
 */
export type PermissionAction =
  | 'view'
  | 'create'
  | 'edit'
  | 'edit-own'
  | 'delete'
  | 'upload'
  | 'download'
  | 'archive'
  | 'invite'
  | 'remove'
  | 'manage-roles'
  | 'activity'
  | 'danger'
  | 'manage'
  | 'invoices';
